#!/usr/bin/env ruby

require_relative 'led_3fet'

if __FILE__ == $0 then
	options = {
		:address => 0x8a # Use the spi_3fets board by default
	}
	options[:address] = ARGV[1] if ARGV[1]

	led = RGBLed.new options

	puts "Current color:", "  RGB: #{led.get_rgb}", "  HSV: #{led.get_hsv}"

	puts "Starting color wheel rotation - 10 degrees / second with 1 saturation and 0.75 value/brightness;"

	h, s, v = *[0, 1, 0.75]

	while true do 
		h += 1
		h -= 360 if h > 360
		
		led.set_hsv(h, s, v)
		puts "Current color:", "  RGB: #{led.get_rgb}", "  HSV: #{led.get_hsv}" if h % 15 == 0

		sleep(0.1)
	end
end
